input.onPinPressed(TouchPin.P1, function () {
    basic.showString("Globe-O-Meter")
    music.playTone(175, music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(330, music.beat(BeatFraction.Quarter))
    music.playTone(466, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(831, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Breve))
    music.playTone(392, music.beat(BeatFraction.Double))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.playTone(494, music.beat(BeatFraction.Half))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Breve))
    music.playTone(440, music.beat(BeatFraction.Double))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Double))
    music.playTone(622, music.beat(BeatFraction.Breve))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(831, music.beat(BeatFraction.Half))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(440, music.beat(BeatFraction.Half))
    music.playTone(262, music.beat(BeatFraction.Half))
    music.playTone(165, music.beat(BeatFraction.Whole))
    music.playTone(139, music.beat(BeatFraction.Double))
    music.playTone(932, music.beat(BeatFraction.Quarter))
    music.playTone(831, music.beat(BeatFraction.Quarter))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(262, music.beat(BeatFraction.Breve))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(196, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(262, music.beat(BeatFraction.Half))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Double))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(196, music.beat(BeatFraction.Half))
    music.playTone(698, music.beat(BeatFraction.Half))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(831, music.beat(BeatFraction.Breve))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.showNumber(input.temperature())
    basic.showArrow(input.compassHeading())
    servos.P0.run(50)
    pins.digitalWritePin(DigitalPin.P0, 0)
    servos.P0.setAngle(input.compassHeading())
    servos.P0.stop()
})
input.onButtonPressed(Button.B, function () {
    let random = 0
    music.beginMelody(music.builtInMelody(Melodies.Nyan), MelodyOptions.Forever)
    led.plotBarGraph(
    random,
    random
    )
})
